sudo: required
language: python
if: tag IS present

# branches:
#     only:
#     - master

jobs:
    include:
    # - os: linux
    #   dist: bionic
    # python:
    # - "3.8"
    - os: osx
      osx_image: xcode11.3
      python:
      - "3.7"

script:
    - bash build_scripts/build.sh
    - make maybe_publish  # test, build wheel, and (if on tag) publish

deploy:
    provider: releases
    token:
        secure: $(GUTHUB_RELEASES_token)
    file_glob: true
    file: "dist/redstork*.whl"
    overwrite: true
    on:
        tags: true