sudo: required
language: python
# if: tag IS present
dist: bionic

python:
    - "3.8"

branches:
    only:
    - master

script:
    - bash build_scripts/build.sh
    - make maybe_publish  # test, build wheel, and (if on tag) publish

