language: shell
if: tag IS present

jobs:
    include:
    - os: linux
      dist: bionic
      python: "3.8"
    - os: osx
      osx_image: xcode11.3

script:
    - bash build_scripts/build.sh && make maybe_publish
