language: shell
if: tag IS present

jobs:
    include:
    - os: linux
      dist: bionic
      before_install:
        sudo apt-get install python3 python3-pip python3-ven
    - os: osx
      osx_image: xcode11.3

script:
    - bash build_scripts/build.sh && make maybe_publish
