test: off

branches:
  only:
  - master

skip_non_tags: true

environment:
  APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
  GYP_MSVS_VERSION: 2017
  PDFium_BRANCH: chromium/4196
  matrix:
    - PDFium_V8: disabled

platform:
  - x64

configuration:
  - Release

build_script:
  - choco install windows-sdk-10-version-1903-windbg
  - call build_scripts\build.bat

