name: Build

on:
  workflow_dispatch:
    inputs:
      target_os:
        description: Target OS (android|ios|linux|mac|wasm|win)
        type: string
        required: true
      target_cpu:
        description: Target (CPU arm|arm64|x64|x86|wasm)
        type: string
        required: true

jobs:
  build:
    runs-on: ${{ (inputs.target_os == 'ios' || inputs.target_os == 'mac') && 'macos-latest' || inputs.target_os == 'win' && 'windows-2022' || 'ubuntu-22.04' }}
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4
      - name: Set environment variables
        run: |
          export PDFium_TARGET_CPU=${{ inputs.target_cpu }}
          export PDFium_TARGET_OS=${{ inputs.target_os }}
          . steps/00-env.sh
          cat >>$GITHUB_ENV <<END
          PDFium_BUILD_ROOT=$PDFium_BUILD_ROOT
          PDFium_SOURCE_DIR=$PDFium_SOURCE_DIR
          PDFium_BUILD_DIR=$PDFium_BUILD_DIR
          PDFium_TARGET_OS=$PDFium_TARGET_OS
          OS=$OS
          CURRENT_CPU=$CURRENT_CPU
          PDFium_TARGET_CPU=$PDFium_TARGET_CPU
          DEPOT_TOOLS_WIN_TOOLCHAIN=$DEPOT_TOOLS_WIN_TOOLCHAIN
          END
        shell: bash
      - name: Install (1/2)
        run: steps/01-install.sh
        shell: bash
      - name: Checkout PDFium
        run: steps/02-checkout.sh
        shell: bash
        timeout-minutes: 15
      - name: Apply patches
        run: steps/03-patch.sh
        shell: bash
      - name: Install (2/2)
        run: steps/04-install-extra.sh
        shell: bash
      - name: Configure
        run: |
          steps/05-configure.sh
        shell: bash
      - name: Build
        run: steps/06-build.sh
        shell: bash
      - name: Staging
        run: steps/07-stage.sh
        shell: bash
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: redstork-lib-${{ inputs.target_os }}-${{ inputs.target_cpu }}
          path: staging/
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"
      - name: Build wheel
        run: steps/08-wheel.sh
        shell: bash
      - name: Upload wheel
        uses: actions/upload-artifact@v4
        with:
          name: redstork-wheel-${{ inputs.target_os }}-${{ inputs.target_cpu }}
          path: dist/

